Move withdrawal explanation page to the GOV.UK Design System
alphagov/whitehall pull request #6875
Opened 2022-09-30 13:34 UTC by dnkrj

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

### What
[Move the withdrawal explaination page to the GOVUK design system layout.
](https://trello.com/c/LhicV17K/776-move-withdrawal-explanation-page-to-the-govuk-design-system)
### Why
This is part of a Whitehall transition work to move from bootstrap to GOVUK design system.

### Screenshots
![whitehall-admin dev gov uk_government_admin_editions_1_unpublishing_edit(iPad Pro) (1)](https://user-images.githubusercontent.com/9594455/193281165-26dda013-32e4-4655-95a5-d24f56ae9f0e.png)
![whitehall-admin dev gov uk_government_admin_editions_1_unpublishing_edit(iPhone 12 Pro) (1)](https://user-images.githubusercontent.com/9594455/193281150-b9fe54fe-3c3d-40a2-967e-31d446cdc720.png)

#### Before
![whitehall-admin dev gov uk_government_admin_editions_1_unpublishing_edit(iPad Pro)](https://user-images.githubusercontent.com/9594455/193281238-4ca70a66-4d70-4c8e-92d2-827ce062693a.png)
![whitehall-admin dev gov uk_government_admin_editions_1_unpublishing_edit(iPhone 12 Pro)](https://user-images.githubusercontent.com/9594455/193281245-07628361-9167-489e-b010-edf7bc22e1f5.png)

2022-10-05 11:38 UTC, davidtrussler commented on app/views/admin/edition_unpublishing/edit.html.erb
> +<% content_for :page_title, "Edit #{withdrawal_or_unpublishing(@unpublishing.edition)} explaination" %>
I think this is a typo (yeah I know it follows the design) - "explanation" not "explaination"

2022-10-05 11:48 UTC, davidtrussler commented on app/views/admin/edition_unpublishing/edit.html.erb
> +      } %>
As above on "explaination".

2022-10-05 11:49 UTC, davidtrussler commented
Hi @dnkrj - just left a comment about a typo (in three places) but otherwise looks good so can approve when that's done.

2022-10-05 14:08 UTC, dnkrj commented
Good catch! Thanks!

2022-10-05 15:42 UTC, davidtrussler approved these changes
LGTM! 👍

2022-10-07 08:55 UTC, DilwoarH commented on app/views/admin/edition_unpublishing/edit.html.erb
> +    <h2 class="govuk-heading-l govuk-!-margin-bottom-3">Reason for <%= withdrawal_or_unpublishing(@unpublishing.edition) %></h2>
```suggestion
    <%= render "govuk_publishing_components/components/heading", {
        text: withdrawal_or_unpublishing(@unpublishing.edition),
        font_size: "l",
        margin_bottom: 3
    } %>
```

2022-10-07 08:56 UTC, DilwoarH requested changes
Just something very minor

2022-10-07 10:59 UTC, DilwoarH approved these changes
Thanks - looks good

2022-10-10 08:49 UTC, merged