274 organisation translation index page
alphagov/whitehall pull request #7818
Opened 2023-06-15 09:52 UTC by davidgisbey

## Description

This PR moves the organisation translation index page to the GOV.UK Design System

- duplicates the controller tests
- adds the organisation translation index page
- adds confirm destroy endpoint

## Screenshots

<img width="871" alt="image" src="https://github.com/alphagov/whitehall/assets/42515961/3f539a49-6ce5-4930-ac74-5de8ce3416b2">

<img width="568" alt="image" src="https://github.com/alphagov/whitehall/assets/42515961/7a5f1fc1-5869-4984-92a2-df1ef539453d">

## Trello card

https://trello.com/c/JdVibxnr/274-organisation-translations-index-page

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails upgrade.

2023-06-19 16:12 UTC, farahTW approved these changes

2023-06-20 09:30 UTC, chriswhitehouse-tw requested changes
Hi David,

Generally looks good, apart from the organisation translation confirm delete for url.

Also, although the changes to the person translation page, look appropriate, its a bit confusing have the commit in this PR. Perhaps is should be moved to its own PR?

2023-06-20 09:30 UTC, chriswhitehouse-tw commented on app/views/admin/organisation_translations/confirm_destroy.html.erb
> +    <%= form_with url: admin_person_translation_path(@organisation, @translation_locale), method: :delete do %>
this needs to be 'admin_organisation_translation_path'

2023-06-22 11:14 UTC, davidtrussler approved these changes
LGTM 👍

2023-06-22 12:52 UTC, chriswhitehouse-tw commented on app/views/admin/organisation_translations/confirm_destroy.html.erb
> +    <%= form_with url: admin_person_translation_path(@organisation, @translation_locale), method: :delete do %>
updated

2023-06-22 12:53 UTC, chriswhitehouse-tw approved these changes

2023-06-22 12:53 UTC, merged