Topical events Edit and New page to GDS
alphagov/whitehall pull request #7839
Opened 2023-06-21 14:45 UTC by farahTW

This PR transits topical event new and edit page to design system.
It does the following:
Duplicated existing files to legacy and updated the controller
Added  new and edit page with design system.
Updated the single image upload component to handle page specific title ,name and id.
Update add-another-js file to have blank option in select component.

**Screen shots:**
**New Page:**
![image](https://github.com/alphagov/whitehall/assets/131259138/f8b1b6ff-0ed6-4ab7-859b-b4767d907004)
![image](https://github.com/alphagov/whitehall/assets/131259138/c5d4b7db-9bd1-49a1-9625-bcf941674cfd)

**Edit Page:**
![image](https://github.com/alphagov/whitehall/assets/131259138/f5595f6e-09b0-40ba-9a3c-9dbda99362fd)

**Trello:**
https://trello.com/c/jFqvIsza/225-dev-new-edit-topical-event-page

2023-06-23 15:55 UTC, farahTW commented
@nnagewad  managed to fix design review changes as discussed
Still there are few margins I am not able to overwrite as existing components have some default value.Like datefield components and Social media account and Service as per the attached image.
We may discuss more with @davidgisbey or @davidtrussler further.
![04 Add multiple links - New promotional feature](https://github.com/alphagov/whitehall/assets/131259138/f36fe1ed-d5ef-4e06-a7aa-6f66421213c2)

2023-06-27 15:17 UTC, chriswhitehouse-tw requested changes
Hi @farahTW, I've reviewed. Looks to be generally working nicely. Just a few comments to tighten things up a bit.

Happy to discuss if it helps?

2023-06-27 15:17 UTC, chriswhitehouse-tw commented on test/unit/call_for_evidence_test.rb
> +    assert topical_event = call_for_evidence.topical_events.create!(name: "Test", description: "Test", summary: "Test")
ditto, should this be in the add topical events commit?

2023-06-28 09:12 UTC, davidgisbey commented on app/models/topical_event.rb
> +  validates :summary, presence: true
good catch have sorted

2023-06-28 10:14 UTC, davidgisbey commented on features/step_definitions/topical_event_steps.rb
> +  expect { click_button "Delete" }.to change(TopicalEvent, :count).by(-1) unless using_design_system?
Looks like we're actually losing functionality here as we're not testing the new flow.

we need to test that this happens in the design system when they confirm delete

2023-06-28 10:38 UTC, davidgisbey commented on app/views/admin/topical_events/_form.html.erb
> +  <%= link_to("Cancel", admin_topical_events_path, class: "govuk-link") %>
good shout!

2023-06-28 10:38 UTC, davidgisbey commented on app/controllers/admin/topical_events_controller.rb
> +      @topical_event.social_media_accounts.first.social_media_service.build if @topical_event.social_media_accounts.first.social_media_service_id.blank?
have done 👍

2023-06-28 13:25 UTC, davidgisbey commented
Currently we don't have a way to delete a topical event in our new implementation. I'm going to add the endpoint and push it up as a separate commit

2023-06-28 13:51 UTC, chriswhitehouse-tw commented on features/step_definitions/topical_event_steps.rb
> +  expect { click_button "Delete" }.to change(TopicalEvent, :count).by(-1) unless using_design_system?
Ah, this might be one to discuss with @nnagewad. As I believe his intention was to remove the Delete button?

2023-06-28 17:45 UTC, chriswhitehouse-tw approved these changes
LGTM

2023-06-28 17:45 UTC, merged