Fix:Hide Edit link when user has no GDS Editor permission.
alphagov/whitehall pull request #8391
Opened 2023-10-20 17:32 UTC by farahTW

This PR added logic to hide the "Edit" link at 'Individual User' page, when logged in user has no 'GDS Editor' permission.

It does the following:
Added helper method to 'show' view to hide "Edit" link based on the user permission.

**Screen shots:**
**User with GDS Editor permission:**
![image](https://github.com/alphagov/whitehall/assets/131259138/60375bf8-1b56-435a-8f6b-84f07e19a930)

**User without GDS Editor permission:**
![image](https://github.com/alphagov/whitehall/assets/131259138/0378bfe8-cc85-4869-ab95-ef9d76212431)

**Trello:**
https://trello.com/c/5CLy1wbs/582-fix-individual-user-page-to-hide-edit-link-when-user-has-no-gds-editor-permission

2023-10-23 09:53 UTC, minhngocd commented
Can we add a test to catch this, please?

2023-10-23 09:53 UTC, minhngocd requested changes
Can we add a test to catch this scenario, please?

2023-10-23 10:52 UTC, farahTW commented
> Can we add a test to catch this scenario, please?

Hi Minno
Test exists for this scenario

2023-10-24 08:31 UTC, mtaylorgds commented on test/functional/admin/users_controller_test.rb
> +  view_test "show: hides Edit link if user has no gds editor permission to edit the record or display the link if user has gds editor permission." do
I think this might be clearer as two separate tests—one with permission, and one without?

2023-10-24 09:02 UTC, minhngocd approved these changes
👍

2023-10-24 09:24 UTC, merged