625 admin legacy styles
alphagov/whitehall pull request #8522
Opened 2023-11-17 12:50 UTC by davidtrussler

- app/assets/stylesheets/admin_legacy/_document.scss
- app/assets/stylesheets/admin_legacy/_forms.scss
- app/assets/stylesheets/admin_legacy/_sidebar.scss

2023-11-21 16:11 UTC, RodneyJohnsonGDS commented
Some really good code cleanup here @davidtrussler. Perhaps we can also look at some of the scss files that are unused and still referenced in the _base.scss file. 

- I notice the styles within admin_legacy/helpers/_statistics-announcements.scss are unused and can be removed. 
- Likewise, in the admin_legacy/helpers/_player-container.scss file there are a number of styles that are unused 

May be worthwhile giving a once over to pick up as part of the cleanup; styling that not longer in use.

2023-11-23 09:20 UTC, mtaylorgds requested changes

2023-11-23 09:20 UTC, mtaylorgds commented on app/controllers/admin/link_check_reports_controller.rb
Is it safe to delete this?

There's still a route for it and I get a 404 when trying to do a link check report locally with this controller deleted…

2023-11-23 12:27 UTC, davidtrussler commented on app/controllers/admin/link_check_reports_controller.rb
@mtaylorgds I have restored the deleted files here as discussed.

2023-11-24 10:53 UTC, mtaylorgds approved these changes

2023-11-24 11:08 UTC, merged