Refactor `WorkingGroupPresenter`
alphagov/whitehall pull request #8957
Opened 2024-04-15 15:41 UTC by brucebolt

Renaming the `WorkingGroupPresenter` to be more consistently named compared to the other Publishing API presenters.

Also removes a useless `else`.

2024-04-15 15:49 UTC, jkempster34 approved these changes

2024-04-15 15:49 UTC, jkempster34 commented on app/presenters/publishing_api/policy_group_presenter.rb
> -        ""
Is this empty string important in the frontend app? I.e., will changing this from "" to nil break something?

2024-04-15 15:52 UTC, jkempster34 commented on app/presenters/publishing_api/policy_group_presenter.rb
> -        ""
I didn't read your commit comment 🤦. Ignore this

2024-04-15 16:09 UTC, jkempster34 requested changes
Going back to my earlier comment, I think this will raise errors in Government Frontend.

See this module https://github.com/alphagov/government-frontend/blob/main/app/presenters/content_item/body.rb#L2

Empty strings are propogated through Publishing API, I've just done a test by editing one of the Policy Groups in Whitehall.

2024-04-16 07:11 UTC, brucebolt commented
Good spot!  I've dropped the second commit and just kept the first one which renames the presenter.

2024-04-16 12:05 UTC, merged